### ISSUE TITLE
Arguments do not get passed

### ISSUE THREAD

**Issue by aconite33** [nettitude/RunPE#11]
When running a base64 encoded file via command line, arguments are not appropriately passed to the execution of the command _of some binaries_.

I have used `net.exe` just fine, however Mimikatz and CheekyBlinders both do not get arguments passed appropriately.

```
RunPE Version: Latest
OS: Windows 10
Build: OS Version: 10.0.19045 N/A Build 19045
```

Example running Mimikatz (latest):

![image](https://user-images.githubusercontent.com/3675886/208538361-7af83a82-f79d-42fa-9492-321982be76c0.png)

[....snippet....]

![image](https://user-images.githubusercontent.com/3675886/208538440-6605560e-c35b-4e1a-a33f-6a8b756655b3.png)

As you can see, the execution of the PE works, however the arguments passed are not passed on to the PE.

I am using our C2 to wrap this functionality and passing the arguments, however they do not get executed.

I have also tried the CheekyBlinders (https://github.com/br-sn/CheekyBlinder) PE file, which results in the same issue of arguments not being passed to the PE binary.

You can see executing directly from the file works in both cases

Mimikatz:

![image](https://user-images.githubusercontent.com/3675886/208538693-04387770-4394-46e8-bc9b-219603f6293f.png)

[...snippet...]

![image](https://user-images.githubusercontent.com/3675886/208538793-41b3d6ed-2a80-43b6-9473-831a990dce6d.png)

Notice the highlighted area, where Mimikatz is being passed the Argument 0 instead of just `coffee` and `exit`

CheekyBlinders:

![image](https://user-images.githubusercontent.com/3675886/208539276-0dce0355-a8d5-4ba7-8eba-52d48bee73af.png)

[...snippet...]

![image](https://user-images.githubusercontent.com/3675886/208539355-13cfdb8e-6855-4cd8-9db4-a04da90a3686.png)

Note CheekyBlinders doesn't even execute correctly, however this may because again of the argv[0] being passed instead of argv[1]

**Comment by stryker2k2** [comment]
Nettitude Team - I'm loving your tools and your blogs! Keep it up!

With that said, I am also having some difficulties determining which exectuables can and cannot be ran via RunPE. Just like @aconite33, I cannot successfully perform a RunPE on `mimikatz.exe` the same way I can on `net.exe`.

In order to find the difference, I went back to basic and created a small little trash program. And it seems that the way parameters are being passed aren't quite aligned with the way that I would create a program to receive them.

![capture402](https://user-images.githubusercontent.com/18358246/208800214-890fc2b9-fa9f-447e-8d88-70f8ef2ab6b1.PNG)

I think this might partially (not fully) contribute to the issue that @aconite33 has; namely looking at the "standard module not found" error which could hint at the argv[0] being different than expected.

I don't mind putting some work into this and maybe even making a Pull Request of my own. But, at this point, I'm lost. Do you all have any suggestions?

**Comment by benpturner** [comment]
Thanks - we'll try and take a look!

**Comment by benpturner** [comment]
Interesting when I run "coffee exit" it appears to work 
![image](https://user-images.githubusercontent.com/2518196/210814794-a0242475-2932-4665-9c6e-b667fad098fe.png)

**Comment by benpturner** [comment]
![image](https://user-images.githubusercontent.com/2518196/210814913-8536cf37-780d-4aa7-9a9c-a4ae56ccdc55.png)

**Comment by aconite33** [comment]
@benpturner I just tried running it again, and I'm not getting anything out of the `EXE OUTPUT` section, just under the `[*] Executing loaded PE` :

![image](https://user-images.githubusercontent.com/3675886/210818091-e670e1e1-b516-4315-a4af-eba025cb2f5b.png)


![image](https://user-images.githubusercontent.com/3675886/210818377-3f065d97-53f4-414f-a24c-b09bf2c61f2f.png)



You can see in the second image, that Mimikatz is trying to execute arg[0] as a parameter, which errors out.

**Comment by aconite33** [comment]
Here is the version of Windows I am running, if that makes any difference:


![image](https://user-images.githubusercontent.com/3675886/210819215-e7f52136-c497-4651-aa7a-1bba9feeed21.png)

**Comment by benpturner** [comment]
After [*] Loaded DLLs cleaned up bit I get [*] Retrieving the 'subprocess' output but you dont seem to in your code
![image](https://user-images.githubusercontent.com/2518196/210820208-d42022f5-30b7-4407-8b83-8be1aa13ab33.png)

**Comment by benpturner** [comment]
I'm on Windows 11 to be fair so that could be playing a part

**Comment by benpturner** [comment]
![image](https://user-images.githubusercontent.com/2518196/210820972-be0ad6da-fd9a-45e8-a687-4a8bfa9fac25.png)

Just tested on Win10 too and works

**Comment by aconite33** [comment]
Well now I'm lost as to why this isn't working. I thought it was Win 11 vs. Win 10, but now I'm stumped. The only difference is you're on Win 10 Enterprise and I'm on Win 10 Pro.

**Comment by stryker2k2** [comment]
I'm following along with Win 10.0.19044 in a VM and I'm running into the same issues as @aconite33 :( Maybe... it's not working because I'm using a VM?

**Comment by benpturner** [comment]
Just tested against the latest version of Mimikatz just in case this was a problem too 
![image](https://user-images.githubusercontent.com/2518196/210825028-342f20e1-8a16-45f1-b13a-94ced90c6905.png)

I am not using a VM at the moment to test this, let me try that..

**Comment by benpturner** [comment]
![image](https://user-images.githubusercontent.com/2518196/210825599-932f8b8b-0cd2-4aba-8f18-726f9ed9f767.png)

**Comment by benpturner** [comment]
This was a VM now too

**Comment by benpturner** [comment]
This isnt getting gripped by MDE or something is it?

**Comment by aconite33** [comment]
@benpturner are you compiling the binary in any specific way? I'm using Visual Studio 2019 and compiling x64. Is there any other steps we should be doing?

**Comment by aconite33** [comment]
@benpturner Same on Windows 11, Mimikatz (latest).
 
![image](https://user-images.githubusercontent.com/3675886/210867032-0272b1c4-8511-4c27-842d-f331fa786c76.png)


![image](https://user-images.githubusercontent.com/3675886/210867167-bf12f101-3efc-4c8a-80bb-aa4faebb0efd.png)


Using latest Windows 11 build.

**Comment by aconite33** [comment]
@benpturner can you provide a build exe that you are using? I just want to make sure it's not a compiling issue on my side.

**Comment by aconite33** [comment]
@m0rv4i I can confirm that the behavior is same in our C2 (Not publicly available) as it is in CLI form.

**Comment by kerrymilan** [comment]
We've made some progress on this, but unfortunately don't yet have a generic solution. When a program instantiated via RunPE reads args directly from `argv`, the values it sees are offset by one due to the `RunPE.exe` path at index 0. This is problematic for programs that look for an argument in a specific index, like [CheekyBlinder](https://github.com/br-sn/CheekyBlinder/). Programs that use `GetCommandLineW()`/`CommandLineToArgvW()` do not have this issue. 

Proof of concept:

```
#include <stdio.h>
#include <Windows.h>
#include <shellapi.h>

int main(int argc, char* argv[]) {
	printf("Original argv values:\n");
	for (int i = 0; i < argc; i++) {
		printf("  argv[%d]: %s\n", i, argv[i]);
	}

	int nArgs;
	LPWSTR *szArglist = CommandLineToArgvW(GetCommandLineW(), &nArgs);

	printf("\nValues from CommandLineToArgvW():\n");
	for (int i = 0; i < nArgs; i++) {
		printf("  argv[%d]: %ws\n", i, szArglist[i]);
	}

	return 0;
}
```

```
------------------------ EXE OUTPUT -------------------------

Original argv values:
  argv[0]: C:\users\lab_user\desktop\runpe\RunPE-main\RunPE-main\RunPE\bin\Debug\RunPE.exe
  argv[1]: c:\users\lab_user\desktop\runpe\proj1\test1\x64\Debug\test1.exe

Values from CommandLineToArgvW():
  argv[0]: c:\users\lab_user\desktop\runpe\proj1\test1\x64\Debug\test1.exe


--------------------- END OF EXE OUTPUT ---------------------
```

The cheap fix is to increment the indices of all argv references by one (e.g. `argv[2]` instead of `argv[1]` in [CheekyBlinder.cpp](https://github.com/br-sn/CheekyBlinder/blob/master/CheekyBlinder/CheekyBlinder.cpp#L509) lines 509, 513, etc.

I believe the mimikatz issue referenced above was build-specific; I suspect their release set [`MIMIKATZ_AUTO_COMMAND_START`](https://github.com/gentilkiwi/mimikatz/blob/c78b1cf37c517ae9d0e872447bb103da9fa6034a/inc/globals.h#L43) to `0` instead of `1`. A local build worked as expected.

**Comment by aconite33** [comment]
I updated CheekyBlinders to reflect what @kerrymilan described, and everything is working as intended!
